# Site settings
title: Paul O'Day
email: odaypaul@gmail.com
description: "The personal website and blog of Paul O'Day. I write about Linux, programming (Clojure, Haskell and C are my favorites), philosophy, and whatever else I feel like."
baseurl: ""
url: "http://oday.io"
twitter_username: ertdfgcb
github_username:  ertdfgcb

# Build settings
markdown: kramdown
permalink: pretty
